
package packagemascotas;
import packagemascotas.Mascotas;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class RegistrarMsc extends javax.swing.JPanel {
    
    ArrayList <Mascotas> ListaMascotas = new ArrayList<Mascotas>();

    /**
     * Creates new form RegistrarMsc
     */
    public RegistrarMsc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etiNombreMasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVaciarMasct = new javax.swing.JButton();
        btnGuardarMasct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        etiMascID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiColor = new javax.swing.JTextField();
        etiTsangre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lstEspecie = new javax.swing.JComboBox<>();
        lstTvida = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageclientes/registrar.png"))); // NOI18N
        jLabel1.setText("Registrar Mascota");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("CC. cliente");

        etiCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiCedulaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Nombre M");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Especie");

        btnVaciarMasct.setText("Vaciar");
        btnVaciarMasct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarMasctActionPerformed(evt);
            }
        });

        btnGuardarMasct.setText("Guardar");
        btnGuardarMasct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMasctActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Id Mascota");

        etiMascID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiMascIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Color");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("T de sangre");

        etiColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiColorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Tiempo de vida");

        lstEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "         ", "Perro", "Gato", "Conejo", "Loro" }));

        lstTvida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "               ", "(...) meses", "1 año(s)", "2 años(s)", "3 años(s)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(etiTsangre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiMascID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnVaciarMasct)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnGuardarMasct))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiColor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lstTvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lstEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(etiMascID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(etiTsangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(etiColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lstTvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lstEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVaciarMasct)
                    .addComponent(btnGuardarMasct))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void etiCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiCedulaActionPerformed

    private void btnVaciarMasctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarMasctActionPerformed
        etiCedula.setText("");
        etiNombreMasc.setText("");
        etiMascID.setText("");
        etiTsangre.setText("");
        etiColor.setText("");
        lstTvida.setSelectedIndex(0);
        lstEspecie.setSelectedIndex(0);
        setWhite();
    }//GEN-LAST:event_btnVaciarMasctActionPerformed

    private void btnGuardarMasctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMasctActionPerformed
        Mascotas mascota= new Mascotas(); 
        int validacion = 0;
        String nombreM,CCliente,IDmasc,color,Tsangre,apellido;
        Object tvidaSeleccionado,especieSeleccionada;
        
        nombreM = etiNombreMasc.getText().trim();
        color = etiColor.getText().trim();
        Tsangre =etiTsangre.getText().trim();
        IDmasc = etiMascID.getText();
        tvidaSeleccionado = lstTvida.getSelectedItem();
        especieSeleccionada = lstEspecie.getSelectedItem();
            if (nombreM.equals("")){
               etiNombreMasc.setBackground(Color.red);
               validacion++;         
            }
            
            /*if (CCliente.equals("")){
               etiCedula.setBackground(Color.red);
               validacion++;         
            }/*/
            
            
            if (color.equals("")){
               etiColor.setBackground(Color.red);
               validacion++;
            }   
            
            if (Tsangre.equals("")){
               etiTsangre.setBackground(Color.red);
               validacion++;
            }
            
            if (IDmasc.equals("")){
               etiMascID.setBackground(Color.red);
               validacion++;   
            }
            
            if (tvidaSeleccionado == null || especieSeleccionada == null) {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar un valor para Tiempo de vida y Especie.");
                    return;
            }
            
            
            if (validacion != 0){
                JOptionPane.showMessageDialog(null, "Se deben completar todos los campos");
            } else {
                etiNombreMasc.setBackground(Color.green);
                etiCedula.setBackground(Color.green);
                etiColor.setBackground(Color.green);
                etiTsangre.setBackground(Color.green);
                etiMascID.setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Registro Exitoso");
                
                
            }
    
    // Guardar los datos en un archivo (puedes elegir el tipo de archivo según tus necesidades)
    // Por ejemplo, guardar en un archivo de texto:
    try {
        
        if (!nombreM.isEmpty() && !IDmasc.isEmpty() &&
            !color.isEmpty() && !Tsangre.isEmpty() && !especieSeleccionada.equals(null) && !tvidaSeleccionado.equals(null)) {

            // Escribe los datos en el archivo "clientes.txt"
            FileWriter writer = new FileWriter("mascotas.txt", true);
            writer.write(IDmasc + "," + nombreM + "," +
                color + "," + Tsangre + "," + tvidaSeleccionado + "," + especieSeleccionada +"\n");
            writer.close();

            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            System.out.println("Datos guardados correctamente.");
        } else {
           JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.");
           System.out.println("Por favor, completa todos los campos.");
        }
        
    } catch (IOException ex) {
        System.err.println("Error al guardar los datos: " + ex.getMessage());
    }      

    }//GEN-LAST:event_btnGuardarMasctActionPerformed

    private void etiColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiColorActionPerformed

    private void etiMascIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiMascIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiMascIDActionPerformed
     public void setWhite() {
        etiNombreMasc.setBackground(Color.WHITE);
        etiCedula.setBackground(Color.WHITE);
        etiColor.setBackground(Color.WHITE);
        etiTsangre.setBackground(Color.WHITE);
        etiMascID.setBackground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMasct;
    private javax.swing.JButton btnVaciarMasct;
    private javax.swing.JTextField etiCedula;
    private javax.swing.JTextField etiColor;
    private javax.swing.JTextField etiMascID;
    private javax.swing.JTextField etiNombreMasc;
    private javax.swing.JTextField etiTsangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lstEspecie;
    private javax.swing.JComboBox<String> lstTvida;
    // End of variables declaration//GEN-END:variables
}
